let products=[],cart=JSON.parse(localStorage.getItem('rrival_cart')||'[]'),cfg={},chatState={lang:'en'};const $=id=>document.getElementById(id);const money=n=>'৳'+Number(n||0).toLocaleString('en-BD');
async function api(u,o={}){const r=await fetch(u,{cache:'no-store',...o,headers:{'Content-Type':'application/json',...(o.headers||{})}});if(!r.ok)throw Error((await r.json().catch(()=>({}))).error||'Request failed');return r.json()}
async function loadSettings(){cfg=await api('/api/settings');$('tagline').textContent=cfg.store_tagline||'';$('aboutText').textContent=cfg.about_store||'';[['ig','instagram_link'],['fb','facebook_link'],['tt','tiktok_link'],['wa','whatsapp_link']].forEach(([id,key])=>{const el=$(id),url=String(cfg[key]||'').trim();if(url){el.href=url;el.style.display='flex';el.onclick=null}else{el.style.display='none'}})}
let activeCat='';async function loadProducts(){const q=$('search').value||'';products=await api('/api/products?search='+encodeURIComponent(q));renderProducts()}
function filterCat(c){activeCat=c;renderProducts();document.querySelectorAll('.filters button').forEach(x=>x.classList.toggle('active',x.textContent.toLowerCase().includes(c.toLowerCase())||(c===''&&x.textContent==='ALL')))}
function renderProducts(){const arr=activeCat?products.filter(p=>p.category===activeCat):products;$('products').innerHTML=arr.map(p=>`<article class="card"><div class="pic"><img src="/assets/${p.image}" alt="${esc(p.name)}"></div><div class="cardInfo"><div class="cardTop"><h3>${esc(p.name)}</h3><span class="price">${money(p.price)}</span></div><div class="meta">${esc(p.category)} · ${esc(p.color||'Signature')} · ${p.stock>0?'IN STOCK':'SOLD OUT'}</div><button class="buy" onclick="add(${p.id})" ${p.stock<=0?'disabled':''}>ADD TO BAG</button></div></article>`).join('')||'<p style="color:#777">No pieces found.</p>'}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function add(id){const p=products.find(x=>Number(x.id)===Number(id));if(!p)return;let x=cart.find(i=>Number(i.id)===Number(id));if(x)x.qty++;else cart.push({id:Number(id),qty:1});saveCart();openCart()}
function saveCart(){localStorage.setItem('rrival_cart',JSON.stringify(cart));$('cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0);renderCart()}
function renderCart(){let total=0;$('cartItems').innerHTML=cart.map(i=>{const p=products.find(x=>Number(x.id)===Number(i.id));if(!p)return '';total+=p.price*i.qty;return `<div class="cartRow"><img src="/assets/${p.image}"><div><b>${esc(p.name)}</b><p>${money(p.price)} × ${i.qty}</p><button class="buy" onclick="removeItem(${p.id})">REMOVE</button></div><span class="qty">${money(p.price*i.qty)}</span></div>`}).join('')||'<p style="color:#777">Your bag is empty.</p>';$('cartTotal').textContent=money(total)}
function removeItem(id){cart=cart.filter(x=>Number(x.id)!==Number(id));saveCart()}function openCart(){renderCart();$('cart').classList.add('show')}function closeCart(){$('cart').classList.remove('show')}
function checkout(){if(!cart.length)return alert('Your bag is empty.');closeCart();$('checkout').classList.add('show');$('orderResult').textContent=''}function closeCheckout(){$('checkout').classList.remove('show')}
async function placeOrder(){try{const r=await api('/api/orders',{method:'POST',body:JSON.stringify({customer_name:$('cName').value,phone:$('cPhone').value,address:$('cAddress').value,items:cart})});$('orderResult').innerHTML=`Order confirmed. Your code is <b>${r.order_code}</b><br>Total: ${money(r.total)}<br><small>Save this code for tracking.</small>`;cart=[];saveCart()}catch(e){$('orderResult').textContent=e.message}}
function toggleChat(){const c=$('chat');c.classList.toggle('show');if(c.classList.contains('show')&&!$('msgs').children.length)addBot('Welcome to Rrival. Ask me about products, prices, stock, delivery, payment or orders. You can also place an order directly here.')}
function addBot(t){$('msgs').insertAdjacentHTML('beforeend',`<div class="msg bot">${esc(t).replace(/\n/g,'<br>')}</div>`);$('msgs').scrollTop=$('msgs').scrollHeight}function addUser(t){$('msgs').insertAdjacentHTML('beforeend',`<div class="msg user">${esc(t)}</div>`);$('msgs').scrollTop=$('msgs').scrollHeight}
function setChatLang(lang){chatState.lang=lang;document.querySelectorAll('.quick button').forEach(b=>b.classList.remove('selected'));const el=$(lang==='bn'?'langBN':'langEN');if(el)el.classList.add('selected');addBot(lang==='bn'?'ভাষা বাংলা করা হয়েছে। এখন আপনি বাংলায় Rrival সম্পর্কে প্রশ্ন করতে পারেন।':'Language set to English. Ask me about Rrival products, orders or store information.')}
async function sendChat(){const t=$('chatText').value.trim();if(!t)return;$('chatText').value='';addUser(t);try{const r=await api('/api/chat',{method:'POST',body:JSON.stringify({message:t,state:chatState,lang:chatState.lang})});chatState=r.state||{};addBot(r.reply);if(r.data?.order){addBot('Your order has been sent to the Rrival team.');}}catch(e){addBot('Sorry, the store assistant is temporarily unavailable.')}}function quick(t){$('chatText').value=t;sendChat()}
setTimeout(()=>setChatLang(chatState.lang),0);
async function openAgents(){const a=await api('/api/agents');$('agentList').innerHTML=a.map(x=>{let wa=x.whatsapp||String(x.phone||'').replace(/\D/g,'');if(wa.startsWith('0'))wa='88'+wa.slice(1);return `<div class="agentItem"><b>${esc(x.name)}</b><small>${esc(x.phone)}</small><a href="tel:${esc(x.phone)}">CALL</a>${wa?`<a target="_blank" rel="noopener" href="https://wa.me/${wa}">WHATSAPP</a>`:''}</div>`}).join('')||'<p style="color:#777">No active agent.</p>';$('agents').classList.add('show')}function closeAgents(){$('agents').classList.remove('show')}
loadSettings().then(loadProducts).then(saveCart).catch(console.error);
