const express=require('express');const path=require('path');const crypto=require('crypto');const multer=require('multer');const {createClient}=require('@libsql/client');
const app=express();app.use(express.json({limit:'12mb'}));app.use(express.urlencoded({extended:true}));
const env=k=>process.env[k];
if(!env('TURSO_DATABASE_URL')||!env('TURSO_AUTH_TOKEN')){console.error('Missing TURSO_DATABASE_URL or TURSO_AUTH_TOKEN');process.exit(1)}
const db=createClient({url:env('TURSO_DATABASE_URL'),authToken:env('TURSO_AUTH_TOKEN')});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024}});
const demo=[
['Rrival Noir Overshirt','Overshirts','2890','6990','Black','12','Premium structured cotton overshirt with matte hardware.','noir-overshirt.svg'],
['Rrival Obsidian Tee','T-Shirts','1490','2990','Black','25','Heavyweight 240 GSM cotton essential tee.','obsidian-tee.svg'],
['Rrival Goldline Polo','Polo','2190','4490','Black / Gold','18','Luxury pique polo with subtle gold embroidery.','goldline-polo.svg'],
['Rrival Axis Shirt','Shirts','2490','4990','White','16','Clean-cut premium poplin shirt for elevated everyday wear.','axis-shirt.svg'],
['Rrival Midnight Hoodie','Hoodies','3290','6490','Black','14','Heavy fleece hoodie with tonal Rrival chest mark.','midnight-hoodie.svg'],
['Rrival Regent Blazer','Blazers','5990','11990','Black','8','Sharp single-breasted blazer with satin detail.','regent-blazer.svg'],
['Rrival Motion Cargo','Pants','2690','5490','Charcoal','20','Tapered cargo trouser with premium utility pockets.','motion-cargo.svg'],
['Rrival Crown Jacket','Jackets','4790','8990','Black','10','Minimal bomber jacket with luxury metal trims.','crown-jacket.svg'],
['Rrival Form Trouser','Pants','2390','4890','Black','17','Straight tailored trouser with clean drape.','form-trouser.svg'],
['Rrival Signature Kurta','Traditional','2290','4590','Off White','13','Modern men’s kurta with refined collar construction.','signature-kurta.svg'],
['Rrival Edge Denim','Denim','3190','5990','Indigo','15','Premium straight-fit denim with subtle wash.','edge-denim.svg'],
['Rrival Apex Shirt','Shirts','2590','5290','Olive','11','Relaxed premium shirt designed for contemporary layering.','apex-shirt.svg']
];
async function init(){await db.executeMultiple(`CREATE TABLE IF NOT EXISTS admins(id INTEGER PRIMARY KEY,username TEXT UNIQUE,password_hash TEXT);CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,category TEXT,price INTEGER,old_price INTEGER,color TEXT,stock INTEGER,description TEXT,image TEXT,active INTEGER DEFAULT 1,created_at TEXT);CREATE TABLE IF NOT EXISTS agents(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,phone TEXT,whatsapp TEXT,active INTEGER DEFAULT 1);CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,order_code TEXT UNIQUE,customer_name TEXT,phone TEXT,address TEXT,items_json TEXT,total INTEGER,status TEXT DEFAULT 'Pending',created_at TEXT);CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT);`);
let a=await db.execute('SELECT id FROM admins LIMIT 1');if(!a.rows.length){const h=crypto.createHash('sha256').update(env('ADMIN_PASSWORD')||'admin123').digest('hex');await db.execute({sql:'INSERT INTO admins(username,password_hash) VALUES(?,?)',args:['admin',h]})}
let s=await db.execute('SELECT COUNT(*) c FROM products');if(Number(s.rows[0].c)===0){for(const p of demo)await db.execute({sql:'INSERT INTO products(name,category,price,old_price,color,stock,description,image,active,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)',args:[...p,1,new Date().toISOString()]})}
const defaults={store_name:'Rrival',store_tagline:'Modern menswear. Distinct by design.',about_store:'Rrival is a premium men’s clothing brand built around clean silhouettes, elevated essentials and timeless confidence. Every piece is designed to look refined without trying too hard.',delivery_time:'2–5 business days',delivery_fee:'120',cod_enabled:'true',bkash_number:'',nagad_number:'',instagram_link:'',facebook_link:'',tiktok_link:'',whatsapp_link:'',theme:'black-gold'};for(const [k,v] of Object.entries(defaults))await db.execute({sql:'INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)',args:[k,v]});let ag=await db.execute('SELECT COUNT(*) c FROM agents');if(Number(ag.rows[0].c)===0){await db.execute({sql:'INSERT INTO agents(name,phone,whatsapp,active) VALUES(?,?,?,1)',args:['Rrival Support','01700000000','8801700000000']})}}
function hash(v){return crypto.createHash('sha256').update(v).digest('hex')};function auth(req,res,next){if(req.headers.authorization!=='Bearer '+(process.env.ADMIN_SESSION||'rrival-admin-session'))return res.status(401).json({error:'Unauthorized'});next()}
app.get('/api/settings',async(_,res)=>{const r=await db.execute('SELECT key,value FROM settings');res.json(Object.fromEntries(r.rows.map(x=>[x.key,x.value])))});
app.get('/api/products',async(req,res)=>{const q=(req.query.search||'').trim();let sql='SELECT * FROM products WHERE active=1';let args=[];if(q){sql+=' AND (name LIKE ? OR category LIKE ? OR color LIKE ? OR description LIKE ?)';const x='%'+q+'%';args=[x,x,x,x]}sql+=' ORDER BY id DESC';const r=await db.execute({sql,args});res.json(r.rows)});
app.get('/api/agents',async(_,res)=>{const r=await db.execute('SELECT id,name,phone,whatsapp FROM agents WHERE active=1 ORDER BY id');res.json(r.rows)});
app.post('/api/orders',async(req,res)=>{const {customer_name,phone,address,items}=req.body;if(!customer_name||!phone||!address||!Array.isArray(items)||!items.length)return res.status(400).json({error:'Missing order details'});let total=0;const clean=[];for(const it of items){const r=await db.execute({sql:'SELECT id,name,price,stock,image FROM products WHERE id=? AND active=1',args:[it.id]});if(!r.rows.length)continue;const p=r.rows[0],qty=Math.max(1,Math.min(Number(it.qty)||1,Number(p.stock)));total+=Number(p.price)*qty;clean.push({id:p.id,name:p.name,price:p.price,qty,image:p.image})}if(!clean.length)return res.status(400).json({error:'No valid products'});const code='RRV-'+Date.now().toString(36).toUpperCase();await db.execute({sql:'INSERT INTO orders(order_code,customer_name,phone,address,items_json,total,status,created_at) VALUES(?,?,?,?,?,?,?,?)',args:[code,customer_name,phone,address,JSON.stringify(clean),total,'Pending',new Date().toISOString()]});res.json({ok:true,order_code:code,total})});
app.get('/api/track/:code',async(req,res)=>{const r=await db.execute({sql:'SELECT order_code,status,customer_name,total,created_at FROM orders WHERE order_code=?',args:[req.params.code.toUpperCase()]});res.json(r.rows[0]||null)});
app.post('/api/chat',async(req,res)=>{
 const msg=String(req.body.message||'').trim();
 const prev=req.body.state&&typeof req.body.state==='object'?req.body.state:{};
 const bangla=/[\u0980-\u09FF]/.test(msg); const m=msg.toLowerCase();
 const settings=Object.fromEntries((await db.execute('SELECT key,value FROM settings')).rows.map(x=>[x.key,x.value]));
 const products=(await db.execute('SELECT id,name,category,price,old_price,color,stock,description FROM products WHERE active=1 ORDER BY id DESC')).rows;
 const agents=(await db.execute('SELECT name,phone,whatsapp FROM agents WHERE active=1 ORDER BY id')).rows;
 let state={...prev}; let reply=''; let data={};
 const en=(a,b)=>bangla?b:a;
 const normalize=x=>String(x||'').toLowerCase().replace(/[^a-z0-9\u0980-\u09ff]+/g,' ').trim();
 const findProduct=text=>{const n=normalize(text);let best=null,score=0;for(const p of products){const hay=normalize(`${p.name} ${p.category} ${p.color} ${p.description}`);let sc=0;if(n.includes(normalize(p.name)))sc+=100;for(const w of n.split(/\s+/)){if(w.length>2&&hay.includes(w))sc+=1}if(sc>score){score=sc;best=p}}return score>=2?best:null};
 const isYes=/^(yes|y|yeah|yep|confirm|confirmed|ok|okay|place|order|হ্যাঁ|জি|ঠিক|কনফার্ম|অর্ডার)$/i.test(m);
 const isNo=/^(no|n|cancel|না|বাতিল)$/i.test(m);
 if(state.mode==='confirm'){
   if(isYes){
     const p=products.find(x=>Number(x.id)===Number(state.productId));
     if(!p||Number(p.stock)<=0){state={};reply=en('Sorry, that product is now out of stock.','দুঃখিত, পণ্যটি এখন স্টকে নেই।');}
     else{const qty=Math.max(1,Math.min(Number(state.qty)||1,Number(p.stock)));const total=Number(p.price)*qty;const code='RRV-'+Date.now().toString(36).toUpperCase();await db.execute({sql:'INSERT INTO orders(order_code,customer_name,phone,address,items_json,total,status,created_at) VALUES(?,?,?,?,?,?,?,?)',args:[code,state.customer_name,state.phone,state.address,JSON.stringify([{id:p.id,name:p.name,price:p.price,qty,image:null}]),total,'Pending',new Date().toISOString()]});state={};reply=en(`Order confirmed. Your order code is ${code}. Total: ৳${total.toLocaleString('en-BD')}. Please save the code for tracking.`,`অর্ডার কনফার্ম হয়েছে। আপনার অর্ডার কোড ${code}। মোট: ৳${total.toLocaleString('bn-BD')}। ট্র্যাকিংয়ের জন্য কোডটি সংরক্ষণ করুন।`);data.order={code,total};}
   } else if(isNo){state={};reply=en('No problem. Your order was cancelled.','ঠিক আছে। আপনার অর্ডার বাতিল করা হয়েছে।');}
   else reply=en('Please reply Confirm or Cancel.','দয়া করে Confirm অথবা Cancel লিখুন।');
 } else if(state.mode==='name'){
   if(msg.length<2) reply=en('Please enter your full name.','আপনার পুরো নাম লিখুন।'); else {state.customer_name=msg;state.mode='phone';reply=en('Great. What is your phone number?','ভালো। আপনার ফোন নম্বরটি দিন।');}
 } else if(state.mode==='phone'){
   const phone=msg.replace(/[^0-9+]/g,''); if(phone.length<8)reply=en('Please enter a valid phone number.','দয়া করে সঠিক ফোন নম্বর দিন।'); else {state.phone=phone;state.mode='address';reply=en('Thanks. What is your full delivery address?','ধন্যবাদ। আপনার সম্পূর্ণ ডেলিভারি ঠিকানা দিন।');}
 } else if(state.mode==='address'){
   if(msg.length<8)reply=en('Please enter your complete delivery address.','দয়া করে সম্পূর্ণ ডেলিভারি ঠিকানা লিখুন।'); else {state.address=msg;state.mode='confirm';const p=products.find(x=>Number(x.id)===Number(state.productId));const total=Number(p.price)*(Number(state.qty)||1);reply=en(`Please confirm your order:\n${p.name}\nQuantity: ${state.qty}\nTotal: ৳${total.toLocaleString('en-BD')}\nName: ${state.customer_name}\nPhone: ${state.phone}\nAddress: ${state.address}\n\nReply Confirm to place the order or Cancel.`,`আপনার অর্ডারটি কনফার্ম করুন:\n${p.name}\nপরিমাণ: ${state.qty}\nমোট: ৳${total.toLocaleString('bn-BD')}\nনাম: ${state.customer_name}\nফোন: ${state.phone}\nঠিকানা: ${state.address}\n\nঅর্ডার দিতে Confirm লিখুন, বাতিল করতে Cancel লিখুন।`);}}
 else if(/^(hi|hello|hey|salam|assalam|হাই|হ্যালো|আসসালাম)/i.test(m)) reply=en('Welcome to Rrival. I can help with products, prices, stock, delivery, payment and orders.','Rrival-এ স্বাগতম। আমি product, price, stock, delivery, payment এবং order বিষয়ে সাহায্য করতে পারি।');
 else if(/delivery|deliver|shipping|কত দিন|ডেলিভারি|শিপিং/.test(m)) reply=en(`Delivery usually takes ${settings.delivery_time||'2–5 business days'}. Delivery fee is ৳${Number(settings.delivery_fee||0).toLocaleString('en-BD')}.`,`সাধারণত delivery সময় ${settings.delivery_time||'2–5 business days'}। Delivery fee ৳${Number(settings.delivery_fee||0).toLocaleString('bn-BD')}।`);
 else if(/payment|pay|bkash|nagad|cash|পেমেন্ট|বিকাশ|নগদ|ক্যাশ/.test(m)){let pm=[];if(settings.cod_enabled==='true')pm.push(bangla?'Cash on Delivery':'Cash on Delivery');if(settings.bkash_number)pm.push('bKash');if(settings.nagad_number)pm.push('Nagad');reply=en('Available payment methods: '+(pm.length?pm.join(', '):'Cash on Delivery')+'.','উপলব্ধ payment method: '+(pm.length?pm.join(', '):'Cash on Delivery')+'।');}
 else if(/track|tracking|order status|অর্ডার.*স্ট্যাটাস|ট্র্যাক/.test(m)){const code=m.match(/rrv-[a-z0-9]+/i);if(code){const r=await db.execute({sql:'SELECT order_code,status,total FROM orders WHERE order_code=?',args:[code[0].toUpperCase()]});reply=r.rows.length?en(`Order ${r.rows[0].order_code} is ${r.rows[0].status}. Total: ৳${Number(r.rows[0].total).toLocaleString('en-BD')}.`,`Order ${r.rows[0].order_code} এখন ${r.rows[0].status} অবস্থায় আছে। মোট: ৳${Number(r.rows[0].total).toLocaleString('bn-BD')}।`):en('I could not find that order code.','এই order code-টি খুঁজে পাওয়া যায়নি।')}else reply=en('Please send your order code, for example RRV-ABC123.','আপনার order code দিন, যেমন RRV-ABC123।');}
 else if(/agent|support|contact|যোগাযোগ|এজেন্ট/.test(m)){reply=agents.length?en(`You can contact ${agents[0].name} at ${agents[0].phone}. Use the Agent Contact icon for all active agents.`,`আপনি ${agents[0].name}-এর সাথে ${agents[0].phone} নম্বরে যোগাযোগ করতে পারেন। সব active agent দেখতে Agent Contact icon চাপুন।`):en('No support agent is currently available.','এই মুহূর্তে কোনো support agent available নেই।');}
 else if(/order|buy|purchase|অর্ডার|কিনতে|নেব/.test(m)){const p=findProduct(msg);if(p){if(Number(p.stock)<=0)reply=en(`${p.name} is currently out of stock.`,`দুঃখিত, ${p.name} এখন স্টকে নেই।`);else{const qtyMatch=m.match(/\b(\d+)\b/);state={mode:'name',productId:p.id,qty:Math.max(1,Number(qtyMatch?.[1]||1))};reply=en(`${p.name} — ৳${Number(p.price).toLocaleString('en-BD')}. Quantity: ${state.qty}. What is your full name?`,`ওকে। ${p.name} — ৳${Number(p.price).toLocaleString('bn-BD')}। পরিমাণ: ${state.qty}। আপনার পুরো নামটি দিন।`);}}else reply=en('Sure. Tell me the product name you want to order.','অবশ্যই। আপনি যে product-টি order করতে চান তার নাম লিখুন।');}
 else {
   const matches=products.map(p=>{const n=normalize(msg);const hay=normalize(`${p.name} ${p.category} ${p.color} ${p.description}`);let sc=0;for(const w of n.split(/\s+/)){if(w.length>2&&hay.includes(w))sc++}return [p,sc]}).filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]).slice(0,4).map(x=>x[0]);
   if(matches.length){const enList=matches.map(p=>`• ${p.name} — ৳${Number(p.price).toLocaleString('en-BD')} — ${p.stock>0?'In stock':'Out of stock'}`).join('\n');const bnList=matches.map(p=>`• ${p.name} — ৳${Number(p.price).toLocaleString('bn-BD')} — ${p.stock>0?'স্টকে আছে':'স্টকে নেই'}`).join('\n');reply=en('Here are the closest matches:\n'+enList,'আপনার প্রশ্নের সাথে মিলে যাওয়া product:\n'+bnList);data.products=matches;}
   else if(/price|cost|product|collection|shirt|tee|t-shirt|polo|hoodie|pant|jacket|blazer|kurta|denim|clothing|শার্ট|টি-শার্ট|পোলো|হুডি|জ্যাকেট|প্যান্ট|কাপড়/.test(m)){const list=products.slice(0,6);reply=en('Our current men’s collection:\n'+list.map(p=>`• ${p.name} — ৳${Number(p.price).toLocaleString('en-BD')}`).join('\n'),'আমাদের বর্তমান men’s collection:\n'+list.map(p=>`• ${p.name} — ৳${Number(p.price).toLocaleString('bn-BD')}`).join('\n'));}
   else reply=en('I’m Rrival’s store assistant. I can only help with our clothing, products, prices, stock, delivery, payment, orders and support.','আমি Rrival-এর store assistant। আমি শুধু আমাদের clothing, product, price, stock, delivery, payment, order এবং support বিষয়ে সাহায্য করতে পারি।');
 }
 res.json({reply,state,data});
});
app.post('/api/admin/login',async(req,res)=>{const r=await db.execute({sql:'SELECT password_hash FROM admins WHERE username=?',args:[req.body.username||'admin']});if(r.rows[0]&&r.rows[0].password_hash===hash(req.body.password||''))return res.json({ok:true,token:process.env.ADMIN_SESSION||'rrival-admin-session'});res.status(401).json({error:'Invalid login'})});
app.get('/api/admin/products',auth,async(_,res)=>res.json((await db.execute('SELECT * FROM products ORDER BY id DESC')).rows));app.post('/api/admin/products',auth,async(req,res)=>{const p=req.body;const r=await db.execute({sql:'INSERT INTO products(name,category,price,old_price,color,stock,description,image,active,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)',args:[p.name,p.category,Number(p.price),Number(p.old_price||0),p.color||'',Number(p.stock||0),p.description||'',p.image||'obsidian-tee.svg',1,new Date().toISOString()]});res.json({id:Number(r.lastInsertRowid)})});
app.put('/api/admin/products/:id',auth,async(req,res)=>{const p=req.body;await db.execute({sql:'UPDATE products SET name=?,category=?,price=?,old_price=?,color=?,stock=?,description=?,image=?,active=? WHERE id=?',args:[p.name,p.category,Number(p.price),Number(p.old_price||0),p.color||'',Number(p.stock||0),p.description||'',p.image||'',Number(p.active??1),req.params.id]});res.json({ok:true})});app.delete('/api/admin/products/:id',auth,async(req,res)=>{await db.execute({sql:'DELETE FROM products WHERE id=?',args:[req.params.id]});res.json({ok:true})});
app.get('/api/admin/orders',auth,async(_,res)=>{const r=await db.execute('SELECT * FROM orders ORDER BY id DESC');res.json(r.rows)});app.put('/api/admin/orders/:id',auth,async(req,res)=>{await db.execute({sql:'UPDATE orders SET status=? WHERE id=?',args:[req.body.status,req.params.id]});res.json({ok:true})});
app.get('/api/admin/agents',auth,async(_,res)=>res.json((await db.execute('SELECT * FROM agents ORDER BY id DESC')).rows));app.post('/api/admin/agents',auth,async(req,res)=>{await db.execute({sql:'INSERT INTO agents(name,phone,whatsapp,active) VALUES(?,?,?,?)',args:[req.body.name,req.body.phone||'',req.body.whatsapp||'',Number(req.body.active??1)]});res.json({ok:true})});app.put('/api/admin/agents/:id',auth,async(req,res)=>{await db.execute({sql:'UPDATE agents SET name=?,phone=?,whatsapp=?,active=? WHERE id=?',args:[req.body.name,req.body.phone||'',req.body.whatsapp||'',Number(req.body.active??1),req.params.id]});res.json({ok:true})});app.delete('/api/admin/agents/:id',auth,async(req,res)=>{await db.execute({sql:'DELETE FROM agents WHERE id=?',args:[req.params.id]});res.json({ok:true})});
app.put('/api/admin/settings',auth,async(req,res)=>{for(const [k,v] of Object.entries(req.body)){if(!/^[a-z_]+$/.test(k))continue;await db.execute({sql:'INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value',args:[k,String(v)]})}res.json({ok:true})});app.post('/api/admin/password',auth,async(req,res)=>{if(!req.body.password)return res.status(400).json({error:'Password required'});await db.execute({sql:'UPDATE admins SET password_hash=? WHERE username=?',args:[hash(req.body.password),'admin']});res.json({ok:true})});
app.use('/admin',express.static(path.join(__dirname,'admin')));app.use(express.static(path.join(__dirname,'public')));app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public/index.html')));init().then(()=>app.listen(process.env.PORT||3000,()=>console.log('Rrival running'))).catch(e=>{console.error(e);process.exit(1)});
